/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ExhibitorRegisterRouteImport } from './routes/exhibitor-register'
import { Route as ExhibitorsRouteImport } from './routes/exhibitors'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ShowcasesRouteImport } from './routes/showcases'
import { Route as SpeakersRouteImport } from './routes/speakers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitorRegisterRoute = ExhibitorRegisterRouteImport.update({
  id: '/exhibitor-register',
  path: '/exhibitor-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitorsRoute = ExhibitorsRouteImport.update({
  id: '/exhibitors',
  path: '/exhibitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesRoute = ShowcasesRouteImport.update({
  id: '/showcases',
  path: '/showcases',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/exhibitor-register': typeof ExhibitorRegisterRoute
  '/exhibitors': typeof ExhibitorsRoute
  '/participants': typeof ParticipantsRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/sandbox': typeof SandboxRoute
  '/showcases': typeof ShowcasesRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/exhibitor-register': typeof ExhibitorRegisterRoute
  '/exhibitors': typeof ExhibitorsRoute
  '/participants': typeof ParticipantsRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/sandbox': typeof SandboxRoute
  '/showcases': typeof ShowcasesRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/exhibitor-register': typeof ExhibitorRegisterRoute
  '/exhibitors': typeof ExhibitorsRoute
  '/participants': typeof ParticipantsRoute
  '/partners': typeof PartnersRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/sandbox': typeof SandboxRoute
  '/showcases': typeof ShowcasesRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/exhibitor-register'
    | '/exhibitors'
    | '/participants'
    | '/partners'
    | '/program'
    | '/register'
    | '/resources'
    | '/sandbox'
    | '/showcases'
    | '/speakers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/exhibitor-register'
    | '/exhibitors'
    | '/participants'
    | '/partners'
    | '/program'
    | '/register'
    | '/resources'
    | '/sandbox'
    | '/showcases'
    | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/exhibitor-register'
    | '/exhibitors'
    | '/participants'
    | '/partners'
    | '/program'
    | '/register'
    | '/resources'
    | '/sandbox'
    | '/showcases'
    | '/speakers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ExhibitorRegisterRoute: typeof ExhibitorRegisterRoute
  ExhibitorsRoute: typeof ExhibitorsRoute
  ParticipantsRoute: typeof ParticipantsRoute
  PartnersRoute: typeof PartnersRoute
  ProgramRoute: typeof ProgramRoute
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRoute
  SandboxRoute: typeof SandboxRoute
  ShowcasesRoute: typeof ShowcasesRoute
  SpeakersRoute: typeof SpeakersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitor-register': {
      id: '/exhibitor-register'
      path: '/exhibitor-register'
      fullPath: '/exhibitor-register'
      preLoaderRoute: typeof ExhibitorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitors': {
      id: '/exhibitors'
      path: '/exhibitors'
      fullPath: '/exhibitors'
      preLoaderRoute: typeof ExhibitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases': {
      id: '/showcases'
      path: '/showcases'
      fullPath: '/showcases'
      preLoaderRoute: typeof ShowcasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ExhibitorRegisterRoute: ExhibitorRegisterRoute,
  ExhibitorsRoute: ExhibitorsRoute,
  ParticipantsRoute: ParticipantsRoute,
  PartnersRoute: PartnersRoute,
  ProgramRoute: ProgramRoute,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRoute,
  SandboxRoute: SandboxRoute,
  ShowcasesRoute: ShowcasesRoute,
  SpeakersRoute: SpeakersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
